Repository ES2-UFPI/ecoleta, pull requests merged in 2022-04, with the labels that each got.

#46 [Dev] implementacao das telas basicas para acessar sistema de listagem de r…
  ui/ecoleta/.expo-shared/assets.json
  ui/ecoleta/.gitignore
  ui/ecoleta/App.js
  ui/ecoleta/app.json
  ui/ecoleta/assets/adaptive-icon.png
  ui/ecoleta/assets/favicon.png
  ui/ecoleta/assets/icon.png
  ui/ecoleta/assets/recycle.jpg
  ui/ecoleta/assets/splash.png
  ui/ecoleta/babel.config.js
  ui/ecoleta/package-lock.json
  ui/ecoleta/package.json
  ui/ecoleta/src/screens/Home.js
  ui/ecoleta/src/screens/ItensDoPonto.js
  ui/ecoleta/src/screens/PontoDeColeta.js
  ui/ecoleta/src/screens/Regiao.js
  ui/ecoleta/src/screens/ResgateSacolaFinalizada.js
  ui/ecoleta/src/screens/ResgateSacolaPendente.js
  ui/ecoleta/src/screens/SacolaEntregue.js
  ui/ecoleta/src/screens/SacolaPendente.js
  ui/ecoleta/src/services/api.js
  ui/ecoleta/yarn.lock
Labels: enhancement

#47 [Develop] Adicionando licença MIT
  LICENSE
Labels: documentation

#48 [Develop] ajuste do workflow
  .github/workflows/develop.yml
Labels: bug, documentation, enhancement

#49 [Develop] Criando arquivo contributing
  CONTRIBUTING.md
Labels: documentation

#57 [Develop]finalização da atividade #36
  .DS_Store
  ecoleta-api-rest.json
Labels: enhancement

#63 [Develop]implementação de testes #62
  .DS_Store
  api/.DS_Store
  api/ecoleta-api/.DS_Store
  api/ecoleta-api/tests/.DS_Store
  api/ecoleta-api/tests/Feature/BagRescue/BagRescueTest.php
Labels: enhancement
